"""
Read Stage 2 sweep_summary.csv and write scripts/stage2_winner.env.

Usage (from phase2/):
  python scripts/pick_stage2_winner.py --csv artifacts/refine/stage2/sweep_summary.csv
  source scripts/stage2_winner.env
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

import pandas as pd

# Map run folder suffix to label_smoothing (folder names do not encode ls)
RUN_LS = {
    "run_02_bs1024_lr0.001_wd0.01": 0.05,
    "run_06_bs1024_lr0.001_wd0.01": 0.0,
    "run_07_bs1024_lr0.001_wd0.01": 0.03,
}


def _ls_from_config(run_dir: Path) -> float:
    for name in ("transformer_config.json", "transformer_masked_config.json"):
        cfg_path = run_dir / name
        if cfg_path.exists():
            with open(cfg_path, encoding="utf-8") as f:
                return float(json.load(f).get("label_smoothing", 0.05))
    folder = run_dir.name
    return RUN_LS.get(folder, 0.05)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--csv",
        default="artifacts/refine/stage2/sweep_summary.csv",
        help="sweep_summary.csv from plot_sweep_results.py",
    )
    parser.add_argument(
        "--out",
        default="scripts/stage2_winner.env",
    )
    parser.add_argument(
        "--max-gap",
        type=float,
        default=0.02,
        help="Max train-val acc gap @ best epoch to be eligible",
    )
    args = parser.parse_args()

    df = pd.read_csv(args.csv)
    eligible = df[df["acc_gap_at_best"] <= args.max_gap].copy()
    if eligible.empty:
        eligible = df.copy()
    best = eligible.sort_values("best_val_acc", ascending=False).iloc[0]

    run_dir = Path(best["run_dir"])
    if not run_dir.is_absolute():
        run_dir = Path(".") / run_dir
    ls = _ls_from_config(run_dir)

    lines = [
        "# Generated by scripts/pick_stage2_winner.py",
        f"# Best: {best['run_label']}  val_acc={best['best_val_acc']:.4f}  gap={best['acc_gap_at_best']:.4f}",
        "",
        f"export STAGE2_WINNER_RUN={best['run_label']}",
        f"export STAGE2_WINNER_DIR={best['run_dir']}",
        "export STAGE2_WINNER_CKPT=transformer_best_acc.pt",
        "",
        f"export WIN_BS={int(best['batch_size'])}",
        f"export WIN_LR={best['lr']}",
        f"export WIN_WD={best['weight_decay']}",
        f"export WIN_LS={ls}",
        "export WIN_EPOCHS=80",
        "export WIN_PATIENCE=15",
        "export WIN_TMAX=80",
        "export WIN_WARMUP=3",
        "",
    ]
    out_path = Path(args.out)
    out_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {out_path}")
    print(f"Winner: {best['run_label']}  acc={best['best_val_acc']:.4f}  lr={best['lr']}  wd={best['weight_decay']}  ls={ls}")


if __name__ == "__main__":
    main()
