"""
Export lightweight catalog of ALL test flows for the presentation UI.

Writes presentation/js/test_flow_catalog.js:
  window.TEST_FLOW_CATALOG = [{flowIndex, classId}, ...]  (49,305 entries)

Packet bytes are NOT included — load timelines via API /flow_vis on demand.

  python presentation/scripts/export_flow_catalog.py
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

import joblib
import torch

ROOT = Path(__file__).resolve().parents[2]
PHASE1 = ROOT / "phase1" / "artifacts"
OUT = ROOT / "presentation" / "js" / "test_flow_catalog.js"


def main() -> None:
    tensors = PHASE1 / "test_tensors.pt"
    le_path = PHASE1 / "label_encoder.pkl"
    for p in (tensors, le_path):
        if not p.is_file():
            print(f"Missing {p}", file=sys.stderr)
            sys.exit(1)

    le = joblib.load(le_path)
    data = torch.load(tensors, map_location="cpu", weights_only=False)
    y = data["y"].numpy()

    catalog = [
        {"flowIndex": int(i), "classId": int(le.classes_[int(y[i])])}
        for i in range(len(y))
    ]

    OUT.write_text(
        "/* Auto-generated by presentation/scripts/export_flow_catalog.py */\n"
        "window.TEST_FLOW_CATALOG = "
        + json.dumps(catalog, separators=(",", ":"))
        + ";\n",
        encoding="utf-8",
    )
    print(f"Wrote {len(catalog):,} flows to {OUT} ({OUT.stat().st_size / 1024:.0f} KB)")


if __name__ == "__main__":
    main()
